src/account/urls.py
from django.urls import path

from account.views import (ActivateUser, Disable2fa, PasswordResetView,
                           ProfileView, UserLoginView, UserLogoutView,
                           UserRegistrationView, VerifyMfa)

app_name: str = "account"

urlpatterns = [
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("verify-mfa/", VerifyMfa.as_view(), name="verify_mfa"),
    path("disable-2fa/", Disable2fa.as_view(), name="disable_2fa"),
    path(
        "activate/<str:uuid64>/<str:token>/",
        ActivateUser.as_view(),
        name="activate_user",
    ),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from api.views import (HealthView, ImagesViewSet, SubscriptionPlanView,
                       UserSubscriptionView)

app_name: str = "api"


schema_view = get_schema_view(
    openapi.Info(
        title="Images API",
        default_version="v1",
        description="API for Images",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="sauberr10@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)


router = routers.DefaultRouter()

router.register(r"images", ImagesViewSet, basename="images")
router.register(r"subscriptions", SubscriptionPlanView, basename="subscriptions")
router.register(r"user-subscriptions", UserSubscriptionView, basename="user-subscriptions")

urlpatterns = [
    path("", include(router.urls)),
    path("health/", HealthView.as_view(), name="health"),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls.conf import include

from core.views import (Handler403, Handler404, Handler500, Handler502,
                        Handler503)

urlpatterns = [
    # Django Admin and Jet URLS
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("jet/", include("jet.urls", "jet")),
    path("admin/", admin.site.urls),
    # Main URL
    path("", include("core.urls", namespace="core")),
    # Subscription URL
    path("subscriptions/", include("subscriptions.urls", namespace="subscriptions")),
    # API DRF Auth URL
    path("drf-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # API URL
    path("api/", include("api.urls", namespace="api")),
    # Prometheus URL
    path("", include("django_prometheus.urls")),
    # Account URL
    path("account/", include("account.urls", namespace="account")),
    # Images URL
    path("images/", include("images.urls", namespace="images")),
    # Social Auth URL
    path("social-auth/", include("social_django.urls", namespace="social")),
    # Password reset urls
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="registration/password/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset-password-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = Handler403.as_view()
handler404 = Handler404.as_view()
handler500 = Handler500.as_view()
handler502 = Handler502.as_view()
handler503 = Handler503.as_view()


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls"))),
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/images/urls.py
from django.urls import path

from images.views import ImageCreateView, ImageDetail, ImagesList

app_name: str = "images"

urlpatterns = [
    path("images/", ImagesList.as_view(), name="images"),
    path("images/<int:pk>/", ImageDetail.as_view(), name="image_detail"),
    path("feature/", ImageCreateView.as_view(), name="image_feature"),
]

src/subscriptions/urls.py
from django.urls import path

from subscriptions.views import (ConfirmDeleteSubscription, CreateSubscription,
                                 DeleteSubscription,
                                 DjangoUpdateSubscriptionConfirmed,
                                 PaypalUpdateSubscriptionConfirmed,
                                 UpdateSubscription)

app_name: str = "subscriptions"

urlpatterns = [
    path(
        "create-subscription/<str:subscription_id>/<str:plan>/",
        CreateSubscription.as_view(),
        name="create_subscription",
    ),
    path(
        "update-subscription/<str:subscription_id>/<str:new_plan>/",
        UpdateSubscription.as_view(),
        name="update_subscription",
    ),
    path(
        "delete-subscription/<str:subscription_id>/",
        ConfirmDeleteSubscription.as_view(),
        name="confirm_delete_subscription",
    ),
    path(
        "delete-subscription-confirmed/<str:subscription_id>/",
        DeleteSubscription.as_view(),
        name="delete_subscription",
    ),
    path(
        "paypal-update-subscription-confirmed/",
        PaypalUpdateSubscriptionConfirmed.as_view(),
        name="paypal_update_subscription_confirmed",
    ),
    path(
        "django-update-subscription-confirmed/<str:subscription_id>/",
        DjangoUpdateSubscriptionConfirmed.as_view(),
        name="django_update_subscription_confirmed",
    ),
]

src/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <script src="https://kit.fontawesome.com/ea79e2d2f8.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon/icon.png' %}"/>
    {% block css %} {% endblock %}

</head>
<body>

{% block content %}


{% endblock %}


{% block js %} {% endblock %}


</body>
</html>

src/templates/partials/footer.html
{% load static %}

{% block css %}

<link rel="stylesheet" href="{% static 'css/partials/footer.css' %}">

{% endblock %}

<body>
<footer class="footer">
    <div class="footer-container">
        <div class="row">
            <div class="footer-col">
                <h4>Contact Us</h4>
                <ul>
                    <li><a href="mailto:beauti-gallery@.com">Email: beauti-gallery@.com</a></li>
                    <li><a href="tel:+1 234 567 890">Phone: +1 234 567 890</a></li>
                    <li><a href="#">Address: 123 Main Street, City, Country</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Pages</h4>
                <ul>
                    <li><a href="{% url 'core:index' %}">Home</a></li>
                    <li><a href="{% url 'images:images' %}">Images</a></li>
                    <li><a href="{% url 'core:pricing' %}">Pricing</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Privacy Page & Guarantee</h4>
                <ul>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Guarantee</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Follow Us</h4>
                <div class="social-links">
                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                    <a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        © {% now 'Y' %} Beati-Gallery. All rights reserved.
    </div>
</footer>
</body>

src/templates/partials/images_list.html
{% extends "partials/base.html" %}
{% load static humanize %}


{% block css %}

<link rel="stylesheet" href="{% static 'css/partials/images_list.css' %}">

{% endblock %}


{% block content %}

    {% include 'partials/navbar.html' %}


    <div class="image-container">
        <ul>
            {% for image in images %}
                <li>
                    <h2><a href="">{{ image.title }}</a></h2>
                    <p><strong>Author:</strong> {{ image.author }}</p>
                    <p><strong>Description:</strong> {{ image.description }}</p>
                    <img src="{{ image.image.url }}" alt="{{ image.title }}" width="480" height="320">
                    <p><strong>Created:</strong> {{ image.created_at|date:"F j, Y" }}</p>
                    {#                    <p><strong>Price:</strong> {{ book.price|intcomma }}$</p>#}
                    {#                    <p><strong>Quantity:</strong> {{ book.quantity }}</p>#}
                    {#                    <p><strong>Total Quantity:</strong> {{ book.total_quantity|intcomma }}$</p>#}
                </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

{% block js %}

    <script src="{% static 'js/images_list.js' %}"></script>

{% endblock %}

src/templates/partials/navbar.html
{% load static %}

{% block css %}

<link rel="stylesheet" href="{% static 'css/partials/navbar.css' %}">

{% endblock %}


{% block content %}

<body>
    <div class="top-bar">
    </div>
    <header class="header-separator">
        <div class="navbar">
            <div class="logo">
                <a href="{% url 'core:index' %}"> <img src="{% static 'images/logo/logo.png' %}" alt="logo"> </a>
            </div>
            <ul class="links">
                <li><a href="{% url 'core:index' %}"> Home </a></li>
                <span>|</span>
                <li><a href="{% url 'images:images' %}"> Images </a></li>
                <span>|</span>
                <li><a href="{% url 'core:pricing' %}"> Pricing </a></li>
                <span>|</span>
                <li><a href="{% url 'images:image_feature' %}"> Feature </a></li>
                <span>|</span>
                <li><a href="{% url 'core:contact' %}"> Contact Us </a></li>
                {% if user.is_authenticated %}
                    <span>|</span>
                    <li class="dropdown">
                        <a href="{% url 'account:profile' %}"> Dashboard <i class="dropdown-arrow down"></i></a>
                        <div class="dropdown-content">
                            <a href="{% url 'account:profile' %}" class="dropdown-item"><i class="fa-solid fa-user"></i>
                                <span>Edit Profile</span> <span class="arrow">&#10095;</span></a>
                            {% if user.is_superuser or user.is_staff %}
                                <a href="{% url 'admin:index' %}" class="dropdown-item"><i class="fa-solid fa-gear"></i>
                                    <span>Admin Panel</span> <span class="arrow">&#10095;</span></a>
                            {% endif %}
                            <form id="logout-form" action="{% url 'account:logout' %}" method="POST">
                                {% csrf_token %}
                            </form>
                            <a href="#" class="logout-links"
                               onclick="document.getElementById('logout-form').submit(); return false;"> <i
                                    class="fa-solid fa-right-from-bracket"></i> Logout <span
                                    class="arrow">&#10095;</span></a>
                        </div>
                    </li>
                {% endif %}
            </ul>
            <form id="logout-form" action="{% url 'account:logout' %}" method="POST" style="display: none;">
                {% csrf_token %}
            </form>
            {% if not user.is_authenticated %}
                <a href="{% url 'account:login' %}" class="action_btn_navbar">Sign In / Login </a>
            {% endif %}
            <div class="toggle_btn">
                <div class="line top_line"></div>
                <div class="line middle_line"></div>
                <div class="line bottom_line"></div>
            </div>
        </div>
        <div class="dropdown_menu">
            <li><a href="{% url 'core:index' %}"> Home </a></li>
            <li><a href="{% url 'images:images' %}"> Images </a></li>
            <li><a href="{% url 'core:pricing' %}"> Pricing </a></li>
            <li><a href="{% url 'images:image_feature' %}"> Feature </a></li>
            <li><a href="{% url 'core:contact' %}"> Contact Us </a></li>
            {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#"> Dashboard <i class="dropdown-arrow down"></i></a>
                    <div class="dropdown-content">
                        <a href="{% url 'account:profile' %}"><i class="fa-solid fa-user"></i> Edit Profile </a>
                        {% if user.is_superuser or user.is_staff %}
                            <a href="{% url 'admin:index' %}"><i class="fa-solid fa-gear"></i> Admin Panel </a>
                        {% endif %}
                        <a href="#" onclick="document.getElementById('logout-form').submit(); return false;"><i
                                class="fa-solid fa-right-from-bracket"></i> Logout </a>
                    </div>
                </li>
            {% else %}
                <a href="{% url 'account:login' %}" class="action_btn"> Sign In / Login </a>
            {% endif %}
        </div>
    </header>
    <div style="border-bottom: 1px solid grey;"></div>

    {% for message in messages %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

            <div class="alert-success" role="alert">
                <i class="fa-solid fa-check"></i>
                <h6>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </h6>
            </div>

        {% endif %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

            <div class="alert-error" role="alert">
                <i class="fa-solid fa-circle-xmark"></i>
                <h6>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </h6>
            </div>

        {% endif %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}

            <div class="alert-info" role="alert">
                <i class="fa-solid fa-circle-info"></i>
                <h6>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </h6>
            </div>
        {% endif %}


        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}

            <div class="alert-warning" role="alert">
                <i class="fa-solid fa-circle-info"></i>
                <h6>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </h6>
            </div>
        {% endif %}

    {% endfor %}


</body>

{% block js %}

<script src="{% static 'js/alert.js' %}"></script>
<script src="{% static 'js/drop_menu.js' %}"></script>
<script src="https://kit.fontawesome.com/ea79e2d2f8.js" crossorigin="anonymous"></script>
<script src="{% static 'js/toggle_btn.js' %}"></script>

{% endblock %}

{% endblock %}

src/templates/partials/pricing.html
{% extends 'partials/base.html' %}
{% load static humanize %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/partials/pricing.css' %}">
{% endblock %}

{% block content %}

{% include 'partials/navbar.html' %}

{% csrf_token %}

{% if subscription_id %}
<section class="plans__container">
    <div class="plans">
        <div class="plansHero">
            <h1 class="plansHero__title plansHero__title--subscription">Manage your subscription</h1>
        </div>
        <div class="subscription-card subscription-card--active">
            <div class="card">
                <div class="card__header">
                    <h2>Active Subscription</h2>
                </div>
                <div class="subscription-status-label subscription-status-label--{{ subscription_plan|lower }}">
                    {{ subscription_plan|title }}
                </div>
            </div>
            <div class="subscription-actions">
                <div class="button-group">
                    <div class="button-group-title">Change Plan</div>
                    <div class="button-group-inner">
                        {% if subscription_plan == 'Basic' %}
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Premium' %}"
                               class="button button--upgrade">Upgrade to Premium</a>
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Enterprise' %}"
                               class="button button--upgrade">Upgrade to Enterprise</a>
                        {% elif subscription_plan == 'Premium' %}
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Basic' %}"
                               class="button button--downgrade">Downgrade to Basic</a>
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Enterprise' %}"
                               class="button button--upgrade">Upgrade to Enterprise</a>
                        {% elif subscription_plan == 'Enterprise' %}
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Basic' %}"
                               class="button button--downgrade">Downgrade to Basic</a>
                            <a href="{% url 'subscriptions:update_subscription' subscription_id 'Premium' %}"
                               class="button button--downgrade">Downgrade to Premium</a>
                        {% endif %}
                    </div>
                </div>

                <div class="button-group">
                    <div class="button-group-title">Cancel Subscription</div>
                    <div class="button-group-inner">
                        <a href="{% url 'subscriptions:confirm_delete_subscription' subscription_id %}"
                           class="button button--delete">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="plans__container">
    <div class="plans">
        <div class="plansHero">
            <h1 class="plansHero__title">Choose your plan</h1>
            <p class="plansHero__subtitle">Start with any plan. No contracts, no hidden fees.</p>
        </div>
        <div class="subscription-card subscription-card--inactive">
            <div class="card">
                <div class="card__header">
                    <h2>No Subscription</h2>
                </div>
                <div class="subscription-status-label subscription-status-label--none">
                    No Subscription
                </div>
                <div class="card__desc">
                    Select a plan below to unlock all features.
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}

<section class="plans__container">
    <div class="plans">
        <div class="planItem__container">
            <div class="planItem planItem--free">
                <div class="card">
                    <div class="card__header">
                        <div class="card__icon symbol symbol--rounded"></div>
                        <h2>{{ basic_plan.name }}</h2>
                    </div>
                    <div class="card__desc">{{ basic_plan.description }}</div>
                </div>
                <div class="price">$<span>{{ basic_plan.cost|intcomma }}/ month</span></div>
                <ul class="featureList">
                    <li {% if not basic_plan.has_thumbnail_200px %}class="disabled"{% endif %}>thumbnail_photo_200px</li>
                    <li {% if not basic_plan.has_thumbnail_400px %}class="disabled"{% endif %}>thumbnail_photo_400px</li>
                    <li {% if not basic_plan.has_original_photo %}class="disabled"{% endif %}>original_photo</li>
                    <li {% if not basic_plan.has_binary_link %}class="disabled"{% endif %}>binary_link</li>
                </ul>
                <div id="paypal-button-container-basic"></div>
                <script src="https://www.paypal.com/sdk/js?client-id=AViFM_g_S_EyBgXIsU-k_4QiK8ZWGDcEax1_923d_rG48UOhsPhv8inLaAUUEE-8TverOEUKZneI2DQx&vault=true&intent=subscription"
                        data-sdk-integration-source="button-factory"></script>
                <script>
                    paypal.Buttons({
                        style: {
                            shape: 'pill',
                            color: 'silver',
                            layout: 'vertical',
                            label: 'subscribe'
                        },
                        createSubscription: function (data, actions) {
                            return actions.subscription.create({
                                plan_id: '{{ basic_plan_id }}'
                            });
                        },
                        onApprove: function (data, actions) {
                            const form = document.createElement('form');
                            form.method = 'POST';
                            form.action = '/subscriptions/create-subscription/' + data.subscriptionID + '/Basic/';

                            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                            const csrfInput = document.createElement('input');
                            csrfInput.type = 'hidden';
                            csrfInput.name = 'csrfmiddlewaretoken';
                            csrfInput.value = csrfToken;
                            form.appendChild(csrfInput);

                            document.body.appendChild(form);
                            form.submit();
                        }
                    }).render('#paypal-button-container-basic');
                </script>
            </div>
            <div class="planItem planItem--pro">
                <div class="card">
                    <div class="card__header">
                        <div class="card__icon symbol"></div>
                        <h2>{{ premium_plan.name }}</h2>
                        <div class="card__label label">Best Value</div>
                    </div>
                    <div class="card__desc">{{ premium_plan.description }}</div>
                </div>
                <div class="price">$<span>{{ premium_plan.cost|intcomma }}/ month</span></div>
                <ul class="featureList">
                    <li {% if not premium_plan.has_thumbnail_200px %}class="disabled"{% endif %}>thumbnail_photo_200px</li>
                    <li {% if not premium_plan.has_thumbnail_400px %}class="disabled"{% endif %}>thumbnail_photo_400px</li>
                    <li {% if not premium_plan.has_original_photo %}class="disabled"{% endif %}>original_photo</li>
                    <li {% if not premium_plan.has_binary_link %}class="disabled"{% endif %}>binary_link</li>
                </ul>
                <div id="paypal-button-container-premium"></div>
                <script>
                    paypal.Buttons({
                        style: {
                            shape: 'pill',
                            color: 'gold',
                            layout: 'vertical',
                            label: 'subscribe'
                        },
                        createSubscription: function (data, actions) {
                            return actions.subscription.create({
                                plan_id: '{{ premium_plan_id }}'
                            });
                        },
                        onApprove: function (data, actions) {
                            const form = document.createElement('form');
                            form.method = 'POST';
                            form.action = '/subscriptions/create-subscription/' + data.subscriptionID + '/Premium/';

                            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                            const csrfInput = document.createElement('input');
                            csrfInput.type = 'hidden';
                            csrfInput.name = 'csrfmiddlewaretoken';
                            csrfInput.value = csrfToken;
                            form.appendChild(csrfInput);

                            document.body.appendChild(form);
                            form.submit();
                        }
                    }).render('#paypal-button-container-premium');
                </script>
            </div>
            <div class="planItem planItem--entp">
                <div class="card">
                    <div class="card__header">
                        <div class="card__icon"></div>
                        <h2>{{ enterprise_plan.name }}</h2>
                    </div>
                    <div class="card__desc">{{ enterprise_plan.description }}</div>
                </div>
                <div class="price">$<span style="color: white;">{{ enterprise_plan.cost|intcomma }}/ month</span></div>
                <ul class="featureList">
                    <li {% if not enterprise_plan.has_thumbnail_200px %}class="disabled"{% endif %}>thumbnail_photo_200px</li>
                    <li {% if not enterprise_plan.has_thumbnail_400px %}class="disabled"{% endif %}>thumbnail_photo_400px</li>
                    <li {% if not enterprise_plan.has_original_photo %}class="disabled"{% endif %}>original_photo</li>
                    <li {% if not enterprise_plan.has_binary_link %}class="disabled"{% endif %}>binary_link</li>
                </ul>
                <div id="paypal-button-container-enterprise"></div>
                <script>
                    paypal.Buttons({
                        style: {
                            shape: 'pill',
                            color: 'black',
                            layout: 'vertical',
                            label: 'subscribe'
                        },
                        createSubscription: function (data, actions) {
                            return actions.subscription.create({
                                plan_id: '{{ enterprise_plan_id }}'
                            });
                        },
                        onApprove: function (data, actions) {
                            const form = document.createElement('form');
                            form.method = 'POST';
                            form.action = '/subscriptions/create-subscription/' + data.subscriptionID + '/Enterprise/';

                            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                            const csrfInput = document.createElement('input');
                            csrfInput.type = 'hidden';
                            csrfInput.name = 'csrfmiddlewaretoken';
                            csrfInput.value = csrfToken;
                            form.appendChild(csrfInput);

                            document.body.appendChild(form);
                            form.submit();
                        }
                    }).render('#paypal-button-container-enterprise');
                </script>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'js/2_factor_toggle.js' %}"></script>

{% include 'partials/footer.html' %}

{% endblock %}

src/templates/partials/search.html
{% load static %}


{% block css %}

<link rel="stylesheet" href="{% static 'css/partials/search.css' %}">

{% endblock %}

<div class="search">
    <form class="search-form">
        <i class="fas fa-search"></i>
        <input type="text" name="q" placeholder="Search">
        <button type="submit">Search</button>
    </form>
    <div class="suggestions-box"></div>
</div>